# Generated by Django 5.0.7 on 2024-08-27 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=50)),
                ('accountType', models.CharField(max_length=50)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
                ('categoryType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionTitle', models.CharField(max_length=50)),
                ('transactionType', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=50)),
                ('transactionAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactionDate', models.DateField()),
                ('shopName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('accountName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccApp.account')),
                ('categoryName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccApp.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccApp.user'),
        ),
        migrations.AddField(
            model_name='account',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AccApp.user'),
        ),
    ]
