# Generated by Django 5.0.7 on 2024-08-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AccApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionAmount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transactionDate',
            new_name='date',
        ),
    ]
